### ISSUE TITLE
error during build in Ubuntu 14.04 with MKL library

### ISSUE THREAD

**Issue by tohnperfect** [dmlc/cxxnet#19]
I have the MKL library installed but with ./build.sh I got the following error.

g++ -c -Wall -g -O3 -msse3 -Wno-unknown-pragmas -funroll-loops -I./mshadow/ -o cxxnet_data.o cxxnet/io/cxxnet_data.cpp
In file included from ./mshadow/mshadow/tensor.h:11:0,
                 from cxxnet/io/cxxnet_data.cpp:6:
./mshadow/mshadow/tensor_base.h:76:19: fatal error: mkl.h: No such file or directory
   #include <mkl.h>
                   ^
compilation terminated.
make: *** [cxxnet_data.o] Error 1

I am on Ubuntu 14.04 system with Cuda6.5.

Thank you.

**Comment by hrishikeshvganu** [comment]
Look at the LDFLAGS portion below ( snippet from sample Makefile). Here -L/opt/OpenBLAS/lib/ indicates to include /opt/OpenBLAS/lib/ which is where my blas library files are
```shell
ifeq ($(blas),1)
 LDFLAGS= -L/opt/OpenBLAS/lib/ -L/opt/nvidia/cuda/lib64  -lm -lcudart -lcublas -lcurand -lz `pkg-config --libs opencv` -lopenblas
 CFLAGS+= -DMSHADOW_USE_MKL=0 -DMSHADOW_USE_CBLAS=1
 LDLIBS=/opt/OpenBLAS/lib/
else
 LDFLAGS= -lm -lcudart -lcublas -lmkl_core -lmkl_intel_lp64 -lmkl_intel_thread -liomp5 -lpthread -lcurand -lz `pkg-config --libs opencv`
endif
```shell

**Comment by ziyuang** [comment]
Add `source /opt/intel/bin/compilervars.sh` to your `.bashrc` will solve most MKL path issues.

**Comment by tohnperfect** [comment]
Thanks @hrishikeshvganu and @ziyuang but I still cannot solve the problem.

**Comment by ziyuang** [comment]
The extra line in my `.zshrc` is `source /opt/intel/bin/compilervars.sh intel64`, and

    $ cat /etc/ld.so.conf.d/intel.conf
    /opt/intel/composer_xe_2015.1.133/compiler/lib/intel64
    /opt/intel/composer_xe_2015.1.133/mpirt/lib/intel64
    /opt/intel/composer_xe_2015.1.133/ipp/../compiler/lib/intel64
    /opt/intel/composer_xe_2015.1.133/ipp/lib/intel64
    /opt/intel/composer_xe_2015.1.133/compiler/lib/intel64
    /opt/intel/composer_xe_2015.1.133/mkl/lib/intel64
    /opt/intel/composer_xe_2015.1.133/tbb/lib/intel64/gcc4.4
