### ISSUE TITLE
error during build in Ubuntu 12.04

### ISSUE THREAD

**Issue by adjgiulio** [dmlc/cxxnet#15]
I have a problem installing cxxnet on my PC with Intel i7 on Ubuntu 12.04

The following is the error message

./build.sh blas=1

Fetch mshadow...
Cloning into 'mshadow'...
remote: Counting objects: 1589, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 1589 (delta 8), reused 12 (delta 7)
Receiving objects: 100% (1589/1589), 488.00 KiB | 303 KiB/s, done.
Resolving deltas: 100% (1068/1068), done.
g++ -c -Wall -g -O3 -msse3 -Wno-unknown-pragmas -funroll-loops -I./mshadow/ -DMSHADOW_USE_MKL=0 -DMSHADOW_USE_CBLAS=1 -o cxxnet_data.o cxxnet/io/cxxnet_data.cpp
In file included from ./mshadow/mshadow/tensor.h:11:0,
                 from cxxnet/io/cxxnet_data.cpp:6:
./mshadow/mshadow/tensor_base.h:83:22: fatal error: cublas.h: No such file or directory
compilation terminated.
make: *** [cxxnet_data.o] Error 1

**Comment by sxhfut** [comment]
i also met this problem. now i am downloading nvidia-cuda-toolkit......
